import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{createClient}from"genlayer-js";
import{studionet}from"genlayer-js/chains";
import{ExternalLink,FileSearch,RefreshCw,Scale,WalletCards}from"lucide-react";
import"./styles.css";

const EXPLORER="https://explorer-studio.genlayer.com";
const DEFAULT_CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||"0xC9C416776A42676Ecd8b462465705c0834081678";
const blankCounts={policy_count:0,incident_count:0,assessed_count:0,settled_count:0,total_liability:"0"};
const exampleSource={owner:"Azariavibecode",repo:"SafeSpend-Inquest",commit:"f7e086259ba0244f6bca660215f3f37eefe4aff3",path:"/fixtures/policies/example-policy.md",digest:"ecf0c00801af162466e18536f5fc6f298133f96034a1c62552864f271a2269d1",marker:"## POLICY SAFE-SPEND-001"};
const short=(v="")=>v?`${v.slice(0,7)}…${v.slice(-5)}`:"—";
const parse=v=>{try{return JSON.parse(v)}catch{return null}};
const txId=v=>typeof v==="string"?v:v?.txId;

function App(){
 const[contract,setContract]=useState(localStorage.getItem("ssi-contract")||DEFAULT_CONTRACT),[account,setAccount]=useState(""),[chain,setChain]=useState("");
 const[counts,setCounts]=useState(blankCounts),[policyId,setPolicyId]=useState("0"),[incidentId,setIncidentId]=useState("0"),[policy,setPolicy]=useState(null),[incident,setIncident]=useState(null);
 const[mode,setMode]=useState("inspect"),[label,setLabel]=useState("operations-policy"),[safe,setSafe]=useState(""),[source,setSource]=useState(JSON.stringify(exampleSource,null,2)),[safeTx,setSafeTx]=useState("");
 const[bond,setBond]=useState("1000000000000000"),[busy,setBusy]=useState(""),[notice,setNotice]=useState("Connect a StudioNet wallet to begin."),[lastTx,setLastTx]=useState("");
 const reader=useMemo(()=>createClient({chain:studionet}),[]),valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
 async function connect(){if(!window.ethereum)return setNotice("Browser wallet not found.");const[a]=await window.ethereum.request({method:"eth_requestAccounts"});const c=await window.ethereum.request({method:"eth_chainId"});setAccount(a||"");setChain(c||"");setNotice(c?.toLowerCase()==="0xf22f"?"Wallet connected to StudioNet.":"Switch wallet to StudioNet (61999).");}
 async function refresh(ids={}){if(!valid)return;setBusy("refresh");try{const p=ids.policyId??policyId,i=ids.incidentId??incidentId;setCounts(parse(await reader.readContract({address:contract,functionName:"get_counts",args:[]}))||blankCounts);const[pr,ir]=await Promise.all([reader.readContract({address:contract,functionName:"get_policy",args:[BigInt(p||0)]}),reader.readContract({address:contract,functionName:"get_incident",args:[BigInt(i||0)]})]);const pp=parse(pr),ii=parse(ir);setPolicy(pp?.error?null:pp);setIncident(ii?.error?null:ii);setNotice("Canonical contract state synchronized.");}catch(e){setNotice(`Read failed: ${e.message}`)}finally{setBusy("")}}
 async function write(name,args,value,ids={}){if(!account)return setNotice("Connect wallet first.");if(!valid)return setNotice("Set the deployed contract address.");setBusy(name);setLastTx("");try{const[a,c]=await Promise.all([window.ethereum.request({method:"eth_accounts"}),window.ethereum.request({method:"eth_chainId"})]);if(!a?.[0]||a[0].toLowerCase()!==account.toLowerCase())throw Error("Account changed; reconnect.");if(c?.toLowerCase()!=="0xf22f")throw Error("Wrong network; use StudioNet 61999.");const wallet=createClient({chain:studionet,provider:window.ethereum,account});const hash=txId(await wallet.writeContract({address:contract,functionName:name,args,value:value?BigInt(value):undefined}));if(!hash)throw Error("Missing transaction id");setLastTx(hash);setNotice("Submitted; waiting for FINALIZED consensus…");const receipt=await reader.waitForTransactionReceipt({hash,status:"FINALIZED",interval:3000,retries:70});if((receipt.status_name||receipt.status)!=="FINALIZED")throw Error(`Ended with ${receipt.status_name||receipt.status}`);await refresh(ids);setNotice("Finalized and reconciled from contract readback.");}catch(e){setNotice(`Write failed: ${e.message}`)}finally{setBusy("")}}
 useEffect(()=>{const p=window.ethereum;if(!p)return;const sync=async()=>{const[a,c]=await Promise.all([p.request({method:"eth_accounts"}),p.request({method:"eth_chainId"})]);setAccount(a?.[0]||"");setChain(c||"")};const ac=a=>{setAccount(a?.[0]||"");setPolicy(null);setIncident(null);setNotice("Wallet role changed; records cleared until refresh.")};const cc=c=>{setChain(c);setNotice(c?.toLowerCase()==="0xf22f"?"StudioNet detected.":"Wrong network.")};sync();p.on?.("accountsChanged",ac);p.on?.("chainChanged",cc);return()=>{p.removeListener?.("accountsChanged",ac);p.removeListener?.("chainChanged",cc)}},[]);
 useEffect(()=>{if(valid){localStorage.setItem("ssi-contract",contract);refresh()}},[contract]);
 const action=mode==="policy"?"Register policy":mode==="incident"?"Open incident":!policy?"Select or create a policy":policy.state==="DRAFT"?"Authenticate policy":!incident?"Open a transaction incident":incident.state==="OPEN"?"Freeze runtime evidence":incident.state==="EVIDENCE_FROZEN"?"Run semantic assessment":incident.state==="ASSESSMENT_FINAL"?"Claim settlement":"Case closed";
 return <main><header><a className="brand" href="#top"><img src="/safespend-logo.png"/><span><b>SafeSpend</b><small>INQUEST</small></span></a><button className="wallet" onClick={connect}><WalletCards size={17}/>{account?short(account):"Connect wallet"}</button></header>
 <section className="mast" id="top"><div><p>GENLAYER · TREASURY FORENSICS</p><h1>Policy on one side.<br/><em>Execution truth</em> on the other.</h1><span>Compare sponsor-declared spending rules with independently verified Safe transactions, then settle matched bonds from a bounded consensus result.</span></div><img src="/safespend-logo.png"/></section>
 <section className="contract"><div><small>LIVE CONTRACT</small><strong>{valid?contract:"Awaiting deployment address"}</strong></div><input value={contract} onChange={e=>setContract(e.target.value.trim())} placeholder="0x contract address"/><a className={!valid?"disabled":""} href={valid?`${EXPLORER}/address/${contract}`:"#"} target="_blank">Explorer <ExternalLink size={14}/></a><button onClick={()=>refresh()}><RefreshCw size={15}/></button></section>
 <section className="workspace"><aside><p>CASE INDEX</p><button className={mode==="inspect"?"active":""} onClick={()=>setMode("inspect")}><FileSearch size={17}/>Inspect records</button><button className={mode==="policy"?"active":""} onClick={()=>setMode("policy")}>01 Register policy</button><button className={mode==="incident"?"active":""} onClick={()=>setMode("incident")}>02 Open incident</button><div className="selectors"><label>Policy ID<input value={policyId} onChange={e=>setPolicyId(e.target.value.replace(/\D/g,""))}/></label><label>Incident ID<input value={incidentId} onChange={e=>setIncidentId(e.target.value.replace(/\D/g,""))}/></label><button onClick={()=>refresh()}>Load exact IDs</button></div><dl><dt>Policy</dt><dd>{policy?.state||"NOT LOADED"}</dd><dt>Incident</dt><dd>{incident?.state||"NOT LOADED"}</dd><dt>Verdict</dt><dd className={incident?.verdict||""}>{incident?.verdict||"—"}</dd></dl></aside>
 <article><div className="headline"><span><p>NEXT VALID TRANSITION</p><h2>{action}</h2></span><Scale size={28}/></div>{mode==="policy"&&<div className="form"><label>Policy label<input value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Ethereum Safe address<input value={safe} onChange={e=>setSafe(e.target.value.trim())} placeholder="0x…"/></label><label>Sponsor bond in wei<input value={bond} onChange={e=>setBond(e.target.value.replace(/\D/g,""))}/></label><label>Immutable GitHub policy descriptor<textarea value={source} onChange={e=>setSource(e.target.value)}/></label><button className="primary" disabled={!!busy} onClick={()=>{if(!parse(source))return setNotice("Policy descriptor must be valid JSON.");const id=String(counts.policy_count);setPolicyId(id);setMode("inspect");write("register_policy",[label,safe,source],bond,{policyId:id})}}>Register bonded policy</button></div>}
 {mode==="incident"&&<div className="form"><label>Policy ID<input value={policyId} onChange={e=>setPolicyId(e.target.value.replace(/\D/g,""))}/></label><label>Safe transaction hash<input value={safeTx} onChange={e=>setSafeTx(e.target.value.trim())} placeholder="0x 64-byte Safe transaction hash"/></label><label>Reporter bond in wei<input value={bond} onChange={e=>setBond(e.target.value.replace(/\D/g,""))}/></label><p className="warning">Reporter must differ from the policy sponsor. The bond must exactly match the sponsor bond.</p><button className="primary" disabled={!!busy} onClick={()=>{const id=String(counts.incident_count);setIncidentId(id);setMode("inspect");write("open_incident",[BigInt(policyId||0),safeTx],bond,{incidentId:id})}}>Open bonded incident</button></div>}
 {mode==="inspect"&&<div className="case"><div className="columns"><section><p>DECLARED POLICY</p><h3>{policy?.label||"No policy loaded"}</h3><dl><dt>Safe</dt><dd>{short(policy?.safe)}</dd><dt>Sponsor</dt><dd>{short(policy?.sponsor)}</dd><dt>Bond</dt><dd>{policy?.bond||"—"}</dd></dl></section><section><p>EXECUTED TRANSACTION</p><h3>{incident?short(incident.safe_tx_hash):"No incident loaded"}</h3><dl><dt>Reporter</dt><dd>{short(incident?.reporter)}</dd><dt>Reason</dt><dd>{incident?.reason_code||"—"}</dd><dt>Claimable</dt><dd>{incident?.claim_amount||"—"}</dd></dl></section></div><div className="actionrow">{policy?.state==="DRAFT"&&<button className="primary" onClick={()=>write("authenticate_policy",[BigInt(policyId)])}>Authenticate exact policy bytes</button>}{policy?.state==="ACTIVE"&&!incident&&<button onClick={()=>setMode("incident")}>Open incident with second wallet</button>}{incident?.state==="OPEN"&&<button className="primary" onClick={()=>write("freeze_evidence",[BigInt(incidentId)])}>Verify Safe + Blockscout</button>}{incident?.state==="EVIDENCE_FROZEN"&&<button className="primary" onClick={()=>write("assess_incident",[BigInt(incidentId)])}>Assess against policy</button>}{incident?.state==="ASSESSMENT_FINAL"&&incident.verdict!=="INCONCLUSIVE"&&<button className="primary" onClick={()=>write("claim_settlement",[BigInt(incidentId)])}>Claim settlement</button>}{["ASSESSMENT_FINAL","REFUNDING"].includes(incident?.state)&&incident?.verdict==="INCONCLUSIVE"&&<button className="primary" onClick={()=>write("claim_split_refund",[BigInt(incidentId)])}>Claim my split refund</button>}</div></div>}
 {lastTx&&<a className="tx" href={`${EXPLORER}/transactions/${lastTx}`} target="_blank">Transaction {short(lastTx)} <ExternalLink size={13}/></a>}<p className="notice">{notice}</p></article></section>
 <section className="metrics">{Object.entries(counts).map(([k,v])=><div key={k}><b>{v}</b><span>{k.replaceAll("_"," ")}</span></div>)}</section><footer>GitHub proves registered policy bytes only. Runtime execution requires matching Safe and Blockscout observations. UI status is shown only after FINALIZED contract readback.</footer></main>
}
createRoot(document.getElementById("root")).render(<App/>);
